<?php


/** @var $block \MageDad\BannerManagement\Block\Adminhtml\Banner\Edit\Form */
?>
<div class="entry-edit form-inline" id="magedad-bannerslider">
    <?php echo $block->getFormHtml(); ?>
</div>
<?php echo $block->getChildHtml('form_after'); ?>

<script type="text/x-magento-init">
    {
        "#magedad-bannerslider": {
            "MageDad_BannerSlider/js/view/bannerslider":{
                "templateHtml": "<?php echo $block->escapeJs($block->getTemplateHtml()); ?>",
                "imgUrls": "<?php echo $block->escapeJs($block->getImageUrls()); ?>"
            }
        }
    }
</script>
